name: wenku8
description: "The original wenku8 rewritten in flutter"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  dynamic_color: ^1.7.0
  material_symbols_icons: ^4.2719.3
  shared_preferences: ^2.2.3
  xml: ^6.5.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
